language: php
sudo: false
php:
  - 7.3
  - 7.2
  - 7.1

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - if [[ !$XDEBUG ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
